[build]
  base = "frontend"
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://your-production-backend-url.com"

[context.deploy-preview.environment]
  REACT_APP_BACKEND_URL = "https://your-backend-url.herokuapp.com"